/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AggregateRouteImport } from './routes/aggregate'
import { Route as BuyConstructionMaterialRouteImport } from './routes/buy-construction-material'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryAreasRouteImport } from './routes/delivery-areas'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MSandRouteImport } from './routes/m-sand'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ReadyMixConcreteRouteImport } from './routes/ready-mix-concrete'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoneDustRouteImport } from './routes/stone-dust'
import { Route as AggregateIndexRouteImport } from './routes/aggregate.index'
import { Route as Aggregate10MmRodiRouteImport } from './routes/aggregate.10-mm-rodi'
import { Route as Aggregate20MmRodiRouteImport } from './routes/aggregate.20-mm-rodi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregateRoute = AggregateRouteImport.update({
  id: '/aggregate',
  path: '/aggregate',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyConstructionMaterialRoute = BuyConstructionMaterialRouteImport.update({
  id: '/buy-construction-material',
  path: '/buy-construction-material',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryAreasRoute = DeliveryAreasRouteImport.update({
  id: '/delivery-areas',
  path: '/delivery-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MSandRoute = MSandRouteImport.update({
  id: '/m-sand',
  path: '/m-sand',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyMixConcreteRoute = ReadyMixConcreteRouteImport.update({
  id: '/ready-mix-concrete',
  path: '/ready-mix-concrete',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneDustRoute = StoneDustRouteImport.update({
  id: '/stone-dust',
  path: '/stone-dust',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregateIndexRoute = AggregateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AggregateRoute,
} as any)
const Aggregate10MmRodiRoute = Aggregate10MmRodiRouteImport.update({
  id: '/10-mm-rodi',
  path: '/10-mm-rodi',
  getParentRoute: () => AggregateRoute,
} as any)
const Aggregate20MmRodiRoute = Aggregate20MmRodiRouteImport.update({
  id: '/20-mm-rodi',
  path: '/20-mm-rodi',
  getParentRoute: () => AggregateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aggregate': typeof AggregateRouteWithChildren
  '/buy-construction-material': typeof BuyConstructionMaterialRoute
  '/contact': typeof ContactRoute
  '/delivery-areas': typeof DeliveryAreasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/m-sand': typeof MSandRoute
  '/materials': typeof MaterialsRoute
  '/ready-mix-concrete': typeof ReadyMixConcreteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stone-dust': typeof StoneDustRoute
  '/aggregate/10-mm-rodi': typeof Aggregate10MmRodiRoute
  '/aggregate/20-mm-rodi': typeof Aggregate20MmRodiRoute
  '/aggregate/': typeof AggregateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy-construction-material': typeof BuyConstructionMaterialRoute
  '/contact': typeof ContactRoute
  '/delivery-areas': typeof DeliveryAreasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/m-sand': typeof MSandRoute
  '/materials': typeof MaterialsRoute
  '/ready-mix-concrete': typeof ReadyMixConcreteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stone-dust': typeof StoneDustRoute
  '/aggregate/10-mm-rodi': typeof Aggregate10MmRodiRoute
  '/aggregate/20-mm-rodi': typeof Aggregate20MmRodiRoute
  '/aggregate': typeof AggregateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aggregate': typeof AggregateRouteWithChildren
  '/buy-construction-material': typeof BuyConstructionMaterialRoute
  '/contact': typeof ContactRoute
  '/delivery-areas': typeof DeliveryAreasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/m-sand': typeof MSandRoute
  '/materials': typeof MaterialsRoute
  '/ready-mix-concrete': typeof ReadyMixConcreteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stone-dust': typeof StoneDustRoute
  '/aggregate/10-mm-rodi': typeof Aggregate10MmRodiRoute
  '/aggregate/20-mm-rodi': typeof Aggregate20MmRodiRoute
  '/aggregate/': typeof AggregateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aggregate'
    | '/buy-construction-material'
    | '/contact'
    | '/delivery-areas'
    | '/how-it-works'
    | '/m-sand'
    | '/materials'
    | '/ready-mix-concrete'
    | '/sitemap.xml'
    | '/stone-dust'
    | '/aggregate/10-mm-rodi'
    | '/aggregate/20-mm-rodi'
    | '/aggregate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buy-construction-material'
    | '/contact'
    | '/delivery-areas'
    | '/how-it-works'
    | '/m-sand'
    | '/materials'
    | '/ready-mix-concrete'
    | '/sitemap.xml'
    | '/stone-dust'
    | '/aggregate/10-mm-rodi'
    | '/aggregate/20-mm-rodi'
    | '/aggregate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aggregate'
    | '/buy-construction-material'
    | '/contact'
    | '/delivery-areas'
    | '/how-it-works'
    | '/m-sand'
    | '/materials'
    | '/ready-mix-concrete'
    | '/sitemap.xml'
    | '/stone-dust'
    | '/aggregate/10-mm-rodi'
    | '/aggregate/20-mm-rodi'
    | '/aggregate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AggregateRoute: typeof AggregateRouteWithChildren
  BuyConstructionMaterialRoute: typeof BuyConstructionMaterialRoute
  ContactRoute: typeof ContactRoute
  DeliveryAreasRoute: typeof DeliveryAreasRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MSandRoute: typeof MSandRoute
  MaterialsRoute: typeof MaterialsRoute
  ReadyMixConcreteRoute: typeof ReadyMixConcreteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoneDustRoute: typeof StoneDustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregate': {
      id: '/aggregate'
      path: '/aggregate'
      fullPath: '/aggregate'
      preLoaderRoute: typeof AggregateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-construction-material': {
      id: '/buy-construction-material'
      path: '/buy-construction-material'
      fullPath: '/buy-construction-material'
      preLoaderRoute: typeof BuyConstructionMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-areas': {
      id: '/delivery-areas'
      path: '/delivery-areas'
      fullPath: '/delivery-areas'
      preLoaderRoute: typeof DeliveryAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m-sand': {
      id: '/m-sand'
      path: '/m-sand'
      fullPath: '/m-sand'
      preLoaderRoute: typeof MSandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready-mix-concrete': {
      id: '/ready-mix-concrete'
      path: '/ready-mix-concrete'
      fullPath: '/ready-mix-concrete'
      preLoaderRoute: typeof ReadyMixConcreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone-dust': {
      id: '/stone-dust'
      path: '/stone-dust'
      fullPath: '/stone-dust'
      preLoaderRoute: typeof StoneDustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregate/': {
      id: '/aggregate/'
      path: '/'
      fullPath: '/aggregate/'
      preLoaderRoute: typeof AggregateIndexRouteImport
      parentRoute: typeof AggregateRoute
    }
    '/aggregate/10-mm-rodi': {
      id: '/aggregate/10-mm-rodi'
      path: '/10-mm-rodi'
      fullPath: '/aggregate/10-mm-rodi'
      preLoaderRoute: typeof Aggregate10MmRodiRouteImport
      parentRoute: typeof AggregateRoute
    }
    '/aggregate/20-mm-rodi': {
      id: '/aggregate/20-mm-rodi'
      path: '/20-mm-rodi'
      fullPath: '/aggregate/20-mm-rodi'
      preLoaderRoute: typeof Aggregate20MmRodiRouteImport
      parentRoute: typeof AggregateRoute
    }
  }
}

interface AggregateRouteChildren {
  Aggregate10MmRodiRoute: typeof Aggregate10MmRodiRoute
  Aggregate20MmRodiRoute: typeof Aggregate20MmRodiRoute
  AggregateIndexRoute: typeof AggregateIndexRoute
}

const AggregateRouteChildren: AggregateRouteChildren = {
  Aggregate10MmRodiRoute: Aggregate10MmRodiRoute,
  Aggregate20MmRodiRoute: Aggregate20MmRodiRoute,
  AggregateIndexRoute: AggregateIndexRoute,
}

const AggregateRouteWithChildren = AggregateRoute._addFileChildren(
  AggregateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AggregateRoute: AggregateRouteWithChildren,
  BuyConstructionMaterialRoute: BuyConstructionMaterialRoute,
  ContactRoute: ContactRoute,
  DeliveryAreasRoute: DeliveryAreasRoute,
  HowItWorksRoute: HowItWorksRoute,
  MSandRoute: MSandRoute,
  MaterialsRoute: MaterialsRoute,
  ReadyMixConcreteRoute: ReadyMixConcreteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoneDustRoute: StoneDustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
